# Site settings
title: Silicon Babylon
email: bnmiller@gmail.com
description: "In the valley of many languages stacked to the heavens"
baseurl: ""
url: "http://www.siliconbabylon.com"

# Build settings
permalink: pretty

markdown: kramdown
markdown_ext:  'markdown,mkdown,mkdn,mkd,md'

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "with_toc_data", "fenced_code_blocks"]